### PR TITLE
#166151264 transition from transifex to an open-source alternative

### PR DESCRIPTION
**Pull request by wangonya**
### What does this PR do?
Moves the project translation files to a new open-source translation server.

### Description of Task to be completed?
- [x] Transition from Transifex to an open source translation server
- [x] Update links pointing to transifex to point to Zanata

### How should this be manually tested?
The new translation server can be accessed [here](https://translate.zanata.org/iteration/view/wger-translate/v1).

### What are the relevant pivotal tracker stories?
[#166151264](https://www.pivotaltracker.com/story/show/166151264) 

### Screenshots
Screenshot 2019-06-07 at 08 53 07

### CODE REVIEW

**Comment by willeswa** [comment]
What do you think about adding a screenshot of Zanata?

**Review by willeswa — COMMENTED** [review]
What do you think about adding a screenshot of Zanata?

**Review by willeswa — APPROVED** [review]

**Review by wekesa931 — COMMENTED** [review]
Good work. I can see the translations uploaded and working as expected.

**Review by jmusila — APPROVED** [review]
I think you have done a good job, the translation is working.

**Comment by ceexon** [comment]
It looks great

**Review by ceexon — APPROVED** [review]

**Pull request merged**
