### PR TITLE
#166466091 Configures Middleware

### PR DESCRIPTION
**Pull request by willeswa**
#### Description
Configures middlewares correctly as per Django 2 rules
#### Type of change
- [x] Currently, CSS is not being processed despite having configured whitenoise for this.
- [x] This bug is being caused by outdated middleware configuration
- [x] The PR fixes the bug
#### How Has This Been Tested?
- Clone [this repo](https://github.com/andela/wg-baqi.git) to your local computer
- CD into `wger` and create a virtual env by doing `python3 -m virtualenv venv`
- Activate the virtual env: `source venv/bin/activate` && install requirements `pip install -r requirements.txt`
- Run migrations by invoking the `bootstrap-wger` command as is on the Readme.rst
- Checkout to the `bg-middleware-bug-166466091` branch
- In your browser login as an admin by going to `http://127.0.0.1:8000/en/admin/` 
- If you are already logged in as an admin, you should be able to navigate to `/en/user/api-key/` to get an api key
#### Any background context:
Current configurations will only work if you are logged in as an admin
#### Story ID
[#166466091](https://www.pivotaltracker.com/story/show/166466091)
#### Screenshots
Screen Shot 2019-06-07 at 05 37 06

### CODE REVIEW

**Review by wekesa931 — COMMENTED** [review]
Good work. You can include the login procedure in the PR message to make it easier for one to know how to generate the API key.

**Comment by willeswa** [comment]
> Good work. You can include the login procedure in the PR message to make it easier for one to know how to generate the API key.

Done

**Comment by wangonya** [comment]
Nice. Seems to be working as expected.

**Review by wangonya — COMMENTED** [review]
Nice. Seems to be working as expected.

**Review by jmusila — APPROVED** [review]
Good work @willeswa seems alright to me.

**Pull request merged**
