### PR TITLE
#166151272 enable social authentication

### PR DESCRIPTION
**Pull request by ceexon**
#### What does this PR do?
- Allow users to login  
#### Description of the Tasks to be completed?
- [x] add `POST` endpoint for user login
- [x] write unit tests

#### How should this be manually tested?
- Clone the repository to your local branch

- $ git clone https://github.com/andela/wg-baqi.git
- $ cd to the wg-baqi directory, create a virtual environment and install the dependencies

- `$ cd wg-baqi`
- `$ virtualenv venv`
- `Add .env and get fields from .env_sample`
- `$ source venv/bin/activate`
- `$ pip install -r requirements.txt`
- `Activate bootstrap and run the server`

- `$ invoke bootstrap-wger --settings-path ./wger/settings.py --no-start-server`
- `$ python manage.py runserver`

- Navigate to the endpoint http://127.0.0.1:8000/api/v2/social/auth-login/
- Get twitter, facebook and google keys and add them to the .env
- Required fields are:
- access_secret only required for twitter
   > provider - specifics('google-oauth2' | 'facebook' | 'twitter')
   > access_token - acquire from google, facebook and twitter
   > accsess_token_secret - acquire from twitter
- login the user

#### Sample images
Screenshot 2019-06-08 at 20 36 55

Screenshot 2019-06-08 at 20 37 33

Screenshot 2019-06-08 at 20 13 34

#### What are the relevant pivotal tracker stories?
#166151272

### CODE REVIEW

**Review by wangonya — COMMENTED** [review]
Is this still work in progress? The feature is working as described but tests are failing.

**Comment by ceexon** [comment]
Yeah am working on finding out why the Travis is failing
As it occurs I had forgotten to add some required keys in the environment

**Review by willeswa — COMMENTED** [review]
Is this ready for a merge?

**Comment by caveinn** [comment]
@kburudi, good work with the implementation. Kindly look at the failing tests.

**Review by jmusila — COMMENTED** [review]
Kindly, look into the failing tests

**Pull request merged**
