### PR TITLE
#166575933 Load bower components

### PR DESCRIPTION
**Pull request by wangonya**
### What does this PR do?
Fixes `bower_components` not loading on front end.

### Description of Task to be completed?
- [x] Add `bower.json` file
- [x] Add `post-install` script on `package.json`

### How should this be manually tested?
View the fixed front-end [here](https://wg-baqi-prod.herokuapp.com/en/dashboard).

### What are the relevant pivotal tracker stories?
[#166575933](https://www.pivotaltracker.com/story/show/166575933) 

#### **Before**:
Screenshot 2019-06-10 at 14 51 47

#### **After**:
Screenshot 2019-06-11 at 06 44 49

### CODE REVIEW

**Review by wekesa931 — COMMENTED** [review]
Great work @wangonya. It works well.

**Review by willeswa — APPROVED** [review]
This is great work. LGTM

**Comment by ceexon** [comment]
LGTM 😄

**Review by ceexon — APPROVED** [review]

**Review by jmusila — APPROVED** [review]
LGTM

**Pull request merged**
